### ISSUE TITLE
Switch component breaks with fragments

### ISSUE THREAD

**Issue by andyrichardson** [molefrog/wouter#154]
## About

Hey there! Thanks for the awesome library!

There seems to be an issue with the switch component when fragments are used.

## Reproduction

 - Create a switch component with some child routes.
 - Wrap some of the child routes in a fragment (code below)
 - Add more routes outside of the fragment
 - Load the page on a route that doesn't match any of the routes in the fragment

```tsx
<Switch>
  <>
    {literalRoutes.map((route) => (
        <Route key={route.url} path={route.url}>
          <AppRoute {...route} />
        </Route>
     ))}
  </>   
  <Route key={'fallback'}>
    <Redirect to={'/'} />
   </Route>,
</Switch>
```

### Expected result

Wouter renders the first matching route (or fallback route)

### Actual result

Wouter gives up parsing `Switch` child components after parsing the fragment and renders nothing.

## Additional info

The following example is what I'm using as a workaround for now

```tsx
<Switch>
  {[
    ...literalRoutes.map((route) => (
      <Route key={route.url} path={route.url}>
        <AppRoute {...route} />
      </Route>
    )),
    <Route key={'fallback'}>
      <Redirect to={'/'} />
    </Route>,
  ]}
</Switch>
```

**Comment by molefrog** [comment]
Hi @andyrichardson! Appreciate the kind words:

> Hey there! Thanks for the awesome library!

I'm afraid `Switch` component will only work with routes that are direct children of the component. This is due to the fact that `Switch` iterates over its children and checks their `path` prop. This also means that Switch won't work with components that render routes internally. React-router is no different https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Switch.md#children-node

I don't think there is a simple and reliable solution of this problem. Even if we use context for that: say a switch could create a special object in the context that will be visible to all internal routes, and then a nested route could use that object to detect that it's being rendered inside a switch. But I think it's nearly impossible to achieve the "render the first match" functionality, since the render order of child components isn't something we can rely on (especially with concurrent mode).

**Comment by molefrog** [comment]
This looks more like an implementation constraint, rather than an issue.
What you're using as a workaround seems completely legit to me!

**Comment by jvdsande** [comment]
Hi, continuing the discussion here instead of #155 (sorry for the duplicate), it seems to me that we _could_ handle dynamic arrays, when they are not wrapped inside a Fragment. In @andyrichardson sample, it would then simply become:

```js
<Switch>
  {literalRoutes.map((route) => (
      <Route key={route.url} path={route.url}>
        <AppRoute {...route} />
      </Route>
  ))}
  <Route key={'fallback'}>
    <Redirect to={'/'} />
  </Route>,
</Switch>
```

(Notice, only the fragment has been removed, but the static route does not have to live in the array)

**This does not work at the moment in Wouter**, as neither Fragment nor arrays are handled by the Switch.

But where Fragment are actual JSX elements and therefore are a bit tricky to handle, simple arrays could work just fine in both React and Preact implementation, by using `React.Children.toArray` in React, and `toChildArray` in Preact.

Both functions work the same way: they flatten any nested array, and do not flatten Fragments.

So maybe it is worth it after all to handle this case, simply add `toChildArray` to the `react-deps.js` exports, and have it be equal to `React.Children.toArray` in the React version. What do you think @molefrog ? Is it something you would be interested in supporting, or should we rely on the workaround proposed by @andyrichardson ?

If it's something that we could handle, I'm happy to open a PR with this modification and associated tests.

**Comment by andyrichardson** [comment]
My two cents on this!

It's a confusing bug - took me a while to realize that a fragment was the issue. This is the first library I've come across that doesn't treat fragments as transparent elements (i.e. `if fragment -> traverse children`).

The cost to fix this bug is basically 0.

> That's what Switch does: it only renders the first matching route.

If this isn't a bug, maybe it's worth updating the README to explain that it only renders the first matching **direct child** route.

If you're open to a PR fix, I'm happy to open one!

**Comment by jvdsande** [comment]
@andyrichardson 

As you can see here: https://codesandbox.io/s/gifted-bell-pgvvs

React-Router itself does not correctly handle Fragments, albeit not with the same result. When using a Fragment anywhere inside a Switch, following children are ignored. In my fiddle you can see that `/page1` correctly matches the route outside the Fragment (ignoring the one inside), `/page2` correctly matches the route inside the Fragment (ignoring the one outside), but `/page3` does not match anything.


This is not to say that Wouter should not try to handle Fragments (this is for @molefrog to decide), but to point out that not all libraries handle Fragments correctly.

In the case of Wouter, handling Fragments is **not** a 0-cost fix unfortunately, as it means that it needs to implement a recursive matching, where right now it only have a single loop. This would negatively impact the size of the bundle I guess. But at least detecting Fragments is easily down with `child.type === Fragment` both in React and Preact :)

**Comment by jvdsande** [comment]
For what it's worth, here is a `flattenChildren` method that works both in React and Preact, and that allows us to keep the current loop structure:

```js
const flattenChildren = (children) => {
  return Array.isArray(children)
    ? children.flatMap((c) =>
        c.type === Fragment
          ? flattenChildren(c.props.children)
          : flattenChildren(c)
      )
    : children;
};
```

And here is a variant only handling Arrays:

```js
const flattenChildren = (children) => {
  return Array.isArray(children)
    ? children.flatMap((c) => flattenChildren(c))
    : children;
};```

Both also handles the isArray check, so that is not needed anymore in the Switch component.

The Fragment+Array variant bumps the size by 34 Bytes, from `1.31kB` to `1.34kB`, and obviously leaves the `use-location.js` size untouched at `380B`.
The Array-only variant bumps the size by 15 Bytes, from `1.31kB` to `1.32kB`.

IMHO, 34 bytes is worth it to handle both Arrays and Fragments in this situation. It would actually make Wouter handle this simple case better than React-Router!

**Comment by jvdsande** [comment]
@molefrog 

Since #156 has been merged fixing this, any idea when we can expect a v2.7.1 to drop? 🙂

**Comment by molefrog** [comment]
@jvdsande Sorry, was busy because of the Christmas holidays 😄 I have just published the release!

**Comment by jvdsande** [comment]
@molefrog No problem, I was just wondering :)
Thanks for the release, that's awesome!

**Comment by Bonfims** [comment]
ihave the last version and still have the problem metioned here, i missing something?

**Comment by molefrog** [comment]
@Bonfims well, you are right, this won't work unless there is a `path` prop explicitly defined on a direct child of `Switch`. The reason is that `Switch` simply iterates over it's `children` (as a JSX) and it can't get the path prop unless `App` component is rendered first.
